name = "debts"
compatibility_date = "2024-01-17"
pages_build_output_dir = "./dist"

[[ d1_databases ]]
binding = "DB"
database_name = "debts"
database_id = "6913ae50-23ed-41d0-8150-b218ddb29c6b"
migrations_dir = "drizzle"