name = "debts"
compatibility_date = "2024-01-17"
pages_build_output_dir = "./dist"

[ dev ]
local_protocol = "https"

[[ d1_databases ]]
binding = "DB"
database_name = "debts"
database_id = "204f3209-c52c-4901-a9ff-ea724e46b8b2"
migrations_dir = "drizzle"
